modmap:
  - name: Default
    remap:
      LeftCtrl: LeftAlt
      Muhenkan:
        held: LeftCtrl
        alone: Muhenkan
      LeftAlt:
        held: LeftCtrl
        alone: Muhenkan
      RightCtrl: RightAlt
      Henkan:
        held: RightCtrl
        alone: Henkan
      RightAlt:
        held: RightCtrl
        alone: Henkan
      Space:
        held: Shift_L
        alone: Space
        free_hold: true
      CapsLock:
        held: CapsLock
        alone: Esc
    device:
      not: ["Apple"]
  - name: Mac
    remap:
      LeftMeta:
        held: LeftCtrl
        alone: Muhenkan
      LeftAlt: LeftMeta
      LeftCtrl: LeftAlt
      RightMeta:
        held: RightCtrl
        alone: Henkan
      RightAlt: RightMeta
      Space:
        held: Shift_L
        alone: Space
        free_hold: true
      CapsLock:
        held: CapsLock
        alone: Esc
    device:
      only: ["Apple"]
virtual_modifiers:
  - CapsLock
keymap:
  - remap:
      CapsLock-h: Left
      CapsLock-j: Down
      CapsLock-k: Up
      CapsLock-l: Right
      CapsLock-s: C-SUPER-Alt-Left
      CapsLock-d: SUPER-Q
      CapsLock-f: C-SUPER-Alt-Right
